"""resultados finales en sport_events

Revision ID: 764616ebbe8f
Revises: 911543fec1d1
Create Date: 2026-08-23 12:12:42.831481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764616ebbe8f'
down_revision: Union[str, Sequence[str], None] = '911543fec1d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sport_events', sa.Column('final_home_score', sa.Integer(), nullable=True))
    op.add_column('sport_events', sa.Column('final_away_score', sa.Integer(), nullable=True))
    op.add_column('sport_events', sa.Column('final_positions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sport_events', 'final_positions')
    op.drop_column('sport_events', 'final_away_score')
    op.drop_column('sport_events', 'final_home_score')
    # ### end Alembic commands ###
