"""favorito en sport_events

Revision ID: ab7ae044ac33
Revises: 2c864b567a48
Create Date: 2026-08-23 20:44:06.954566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab7ae044ac33'
down_revision: Union[str, Sequence[str], None] = '2c864b567a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sport_events', sa.Column('favorito', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sport_events', 'favorito')
    # ### end Alembic commands ###
